/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelIconBS = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        labelUserName = new javax.swing.JLabel();
        labelPwd = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        cbRemeberAcc = new javax.swing.JCheckBox();
        labelForgotPwd = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Battle Ship");
        setLocation(new java.awt.Point(550, 150));
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIconBS.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        labelIconBS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-cargo-ship-64.png"))); // NOI18N
        labelIconBS.setText("  BATTLE SHIP");
        labelIconBS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelIconBS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(labelIconBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 160, -1));
        labelIconBS.getAccessibleContext().setAccessibleName("iconBattleShip");

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUserName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 210, 30));
        txtUserName.getAccessibleContext().setAccessibleName("txtUserName");

        labelUserName.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        labelUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelUserName.setText("Username:");
        labelUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(labelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 110, 30));
        labelUserName.getAccessibleContext().setAccessibleName("labelUsername");

        labelPwd.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        labelPwd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPwd.setText("Password:");
        labelPwd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(labelPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));
        labelPwd.getAccessibleContext().setAccessibleName("lablePwd");

        jPasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 210, 30));
        jPasswordField.getAccessibleContext().setAccessibleName("txtPwd");

        cbRemeberAcc.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        cbRemeberAcc.setText("Rememberd Account ?");
        cbRemeberAcc.setBorder(null);
        cbRemeberAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbRemeberAcc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cbRemeberAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRemeberAccActionPerformed(evt);
            }
        });
        jPanel1.add(cbRemeberAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 200, 20));
        cbRemeberAcc.getAccessibleContext().setAccessibleName("cbRememberAcc");

        labelForgotPwd.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        labelForgotPwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-forgot-password-26.png"))); // NOI18N
        labelForgotPwd.setText("Forgotten Password ?");
        labelForgotPwd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(labelForgotPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 200, 40));
        labelForgotPwd.getAccessibleContext().setAccessibleName("iconForgotPwd");

        btnSignIn.setBackground(new java.awt.Color(255, 255, 255));
        btnSignIn.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-enter-40.png"))); // NOI18N
        btnSignIn.setText("Sign In");
        btnSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 210, -1));

        btnSignUp.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-sign-up-40.png"))); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void cbRemeberAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRemeberAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRemeberAccActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        SignUp signup = new SignUp();
        signup.setVisible(true);
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JCheckBox cbRemeberAcc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel labelForgotPwd;
    private javax.swing.JLabel labelIconBS;
    private javax.swing.JLabel labelPwd;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
