/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public SignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelIconBS = new javax.swing.JLabel();
        txtEmail_SignUp = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        labelPwd = new javax.swing.JLabel();
        txtConfrimPwd_SignUp = new javax.swing.JPasswordField();
        cbAgreeTermsPolicy = new javax.swing.JCheckBox();
        labelPwd_SignUp = new javax.swing.JLabel();
        jPasswordField_SignUp = new javax.swing.JPasswordField();
        txtUserName_SignUp = new javax.swing.JTextField();
        labelUserName_SignUp = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        btnSignIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration");
        setLocation(new java.awt.Point(550, 150));
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIconBS.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        labelIconBS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-cargo-ship-64.png"))); // NOI18N
        labelIconBS.setText("  BATTLE SHIP");
        labelIconBS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelIconBS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(labelIconBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 160, -1));
        labelIconBS.getAccessibleContext().setAccessibleName("iconBattleShip");

        txtEmail_SignUp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail_SignUp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmail_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail_SignUpActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 210, 30));
        txtEmail_SignUp.getAccessibleContext().setAccessibleName("txtUserName");

        labelEmail.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEmail.setText("Email:");
        labelEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 110, 30));
        labelEmail.getAccessibleContext().setAccessibleName("labelUsername");

        labelPwd.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        labelPwd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPwd.setText("Confirm Password:");
        labelPwd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(labelPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        labelPwd.getAccessibleContext().setAccessibleName("lablePwd");

        txtConfrimPwd_SignUp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtConfrimPwd_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfrimPwd_SignUpActionPerformed(evt);
            }
        });
        jPanel1.add(txtConfrimPwd_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 210, 30));
        txtConfrimPwd_SignUp.getAccessibleContext().setAccessibleName("txtPwd");

        cbAgreeTermsPolicy.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        cbAgreeTermsPolicy.setText("Agree with Terms & Policy");
        cbAgreeTermsPolicy.setBorder(null);
        cbAgreeTermsPolicy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbAgreeTermsPolicy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cbAgreeTermsPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgreeTermsPolicyActionPerformed(evt);
            }
        });
        jPanel1.add(cbAgreeTermsPolicy, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 230, 20));
        cbAgreeTermsPolicy.getAccessibleContext().setAccessibleName("cbAgreeTermsPolicy");

        labelPwd_SignUp.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        labelPwd_SignUp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPwd_SignUp.setText("Password:");
        labelPwd_SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(labelPwd_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jPasswordField_SignUp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_SignUpActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 210, 30));

        txtUserName_SignUp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUserName_SignUp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUserName_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserName_SignUpActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserName_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 210, 30));

        labelUserName_SignUp.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        labelUserName_SignUp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelUserName_SignUp.setText("Username:");
        labelUserName_SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(labelUserName_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, 30));

        btnSignUp.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-sign-up-40.png"))); // NOI18N
        btnSignUp.setText("Register");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 250, -1));

        btnSignIn.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-enter-40.png"))); // NOI18N
        btnSignIn.setText("Click here to Sign In");
        btnSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmail_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail_SignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail_SignUpActionPerformed

    private void txtConfrimPwd_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfrimPwd_SignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfrimPwd_SignUpActionPerformed

    private void cbAgreeTermsPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgreeTermsPolicyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAgreeTermsPolicyActionPerformed

    private void jPasswordField_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_SignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_SignUpActionPerformed

    private void txtUserName_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserName_SignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserName_SignUpActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnSignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JCheckBox cbAgreeTermsPolicy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_SignUp;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelIconBS;
    private javax.swing.JLabel labelPwd;
    private javax.swing.JLabel labelPwd_SignUp;
    private javax.swing.JLabel labelUserName_SignUp;
    private javax.swing.JPasswordField txtConfrimPwd_SignUp;
    private javax.swing.JTextField txtEmail_SignUp;
    private javax.swing.JTextField txtUserName_SignUp;
    // End of variables declaration//GEN-END:variables
}
